-- Create a table for bookings
drop table if exists bookings;

create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  destination text,
  departure text,
  travel_date text,
  number_of_people integer,
  email text,
  phone text
);
